// ============================================
// MAGAZINE DATA — 9 catalogs with editorial pages
// ============================================

const img = (k, s) => window.umbriaImg(k, s);

window.UMBRIA_MAGAZINES = [
  // 1. BODAS 2026-2027 — Emmanuel Umbría
  {
    id: "bodas",
    unit: "Emmanuel Umbría",
    icon: "💍",
    brand: "Emmanuel Umbría",
    title: "Colección Bodas · 2026-2027",
    accent: "burgundy",
    coverImage: img("weddingBW", 21),
    pages: [
      { layout: "cover", brand: "EMMANUEL UMBRÍA", eyebrow: "Colección 2026-2027",
        titleParts: [{ text: "WEDDING" }, { text: "ATELIER", italic: true }],
        script: "Tu historia, en portada",
        image: img("weddingBW", 21), edition: "2026", no: "01" },
      { layout: "index", eyebrow: "Contenido",
        titleParts: [{ text: "EN ESTA" }, { text: "edición", italic: true }],
        items: [
          { name: "Nuestra filosofía", page: 4 },
          { name: "Cómo trabajamos", page: 6 },
          { name: "Pack Esencial", page: 8 },
          { name: "Pack Atelier", page: 10 },
          { name: "Pack Signature", page: 12 },
          { name: "Reserva tu fecha", page: 14 },
        ]},
      { layout: "fullImage", image: img("weddingGolden", 22),
        captionLabel: "Boda · Golden Hour",
        caption: "Cada boda comienza con una conversación de tú a tú — ninguna se gestiona por un formulario." },
      { layout: "imageText", image: img("weddingMoody", 23),
        eyebrow: "Filosofía",
        titleParts: [{ text: "EL DETALLE" }, { text: "que dura", italic: true }],
        script: "lo cotidiano se vuelve recuerdo",
        body: "Para Emmanuel, fotografiar bodas es escuchar antes que disparar. Llegamos temprano, conocemos a las familias, anticipamos los gestos pequeños — porque ahí vive la verdadera memoria del día." },
      { layout: "quote",
        quote: "Quería un fotógrafo que entendiera a mi mamá tanto como a mí. Emmanuel lo logró sin que se lo pidiera.",
        by: "Fernanda · Novia 2024" },
      { layout: "package", eyebrow: "Boda · Pack 01", no: "01",
        titleParts: [{ text: "Esencial" }],
        price: "1.290.000",
        list: [
          "Cobertura fotográfica 6 horas",
          "300+ imágenes editadas",
          "Galería web privada de alta resolución",
          "Reunión previa de planificación",
          "Entrega en 30 días",
        ],
        note: "Reserva con 50% de adelanto · Saldo 7 días antes del evento" },
      { layout: "package", eyebrow: "Boda · Pack 02", no: "02",
        titleParts: [{ text: "Atelier", italic: true }],
        price: "1.890.000",
        list: [
          "Cobertura fotográfica 10 horas",
          "500+ imágenes editadas",
          "Sesión pre-boda golden hour",
          "Galería web privada + USB de madera",
          "Photobook 30x30 cm impreso",
        ],
        note: "El más elegido · Incluye preparativos de novia y novio" },
      { layout: "imageText", image: img("weddingGolden", 25),
        eyebrow: "Lo que incluye",
        titleParts: [{ text: "TODO" }, { text: "lo que importa", italic: true }],
        list: [
          "Asesoría previa con Emmanuel en persona",
          "Vista del lugar y plan de cobertura",
          "Edición artesanal cuadro por cuadro",
          "Portal web privado durante 1 año",
          "Soporte WhatsApp directo durante el proceso",
        ]},
      { layout: "package", eyebrow: "Boda · Pack 03", no: "03",
        titleParts: [{ text: "Signature" }],
        price: "2.890.000",
        list: [
          "Cobertura fotográfica 12 horas + video resumen",
          "800+ imágenes editadas",
          "Sesión pre-boda + post-boda",
          "Photobook premium 35x35 + 2 mini para padres",
          "Caja editorial impresa firmada",
        ],
        note: "Ideal para bodas con más de 120 invitados" },
      { layout: "credits", tag: "Hablemos" },
    ],
  },

  // 2. 10 CONSEJOS PARA TU BODA
  {
    id: "consejos",
    unit: "Emmanuel Umbría",
    icon: "💡",
    brand: "Emmanuel Umbría",
    title: "10 Consejos · Para tu Boda",
    coverImage: img("weddingMoody", 31),
    pages: [
      { layout: "cover", brand: "EMMANUEL UMBRÍA", eyebrow: "Guía gratuita",
        titleParts: [{ text: "10 CONSEJOS" }, { text: "para tu boda", italic: true }],
        script: "de Emmanuel y Rosa",
        image: img("weddingMoody", 31), no: "02" },
      { layout: "twoColumn", eyebrow: "Introducción",
        titleParts: [{ text: "ANTES DE" }, { text: "empezar", italic: true }],
        body: "Hemos cubierto cientos de bodas y cada pareja nos enseña algo. Estos diez consejos son los que más veces hubiéramos querido susurrarle al oído a la novia al final del día.",
        body2: "No son reglas — son atajos para que disfrutes más, te estreses menos, y termines con fotos que cuenten quiénes son. Léelos sin prisa." },
      { layout: "imageText", image: img("weddingGolden", 32),
        eyebrow: "Consejo 01",
        titleParts: [{ text: "ELIGE" }, { text: "la luz", italic: true }],
        body: "La hora dorada existe por algo. Si la ceremonia es a las 18:00 en verano, tendrás 40 minutos mágicos para la sesión de pareja. Pídele a tu fotógrafo que la agende." },
      { layout: "imageText", image: img("weddingBW", 33),
        eyebrow: "Consejo 02",
        titleParts: [{ text: "SUELTA" }, { text: "el plan", italic: true }],
        body: "Los mejores momentos no se ensayan. Tu abuela llorando cuando te ve entrar, tu pareja riéndose del discurso de su mejor amigo — eso es lo que vamos a buscar." },
      { layout: "imageText", image: img("weddingGolden", 34),
        eyebrow: "Consejo 03",
        titleParts: [{ text: "COME" }, { text: "y bebe", italic: true }],
        body: "Suena obvio. No lo es. La adrenalina del día oculta el hambre. Te dejamos un sandwich y agua en el preparativo — siempre. Tu cara a las 22:00 nos lo agradece." },
      { layout: "quote",
        quote: "Aprendimos que la mejor foto de boda es la que no pediste. Para eso hay que estar — no actuar.",
        by: "Emmanuel · Fotógrafo" },
      { layout: "twoColumn", eyebrow: "Consejos 04 a 07",
        titleParts: [{ text: "EN LA" }, { text: "iglesia y fiesta", italic: true }],
        body: "04 · Reserva 20 minutos para retratos de familia inmediatamente después de la ceremonia. La gente se dispersa rápido. 05 · Avisa a tus papás con anticipación: ellos también quieren su foto.",
        body2: "06 · Un brindis íntimo de 10 personas vale más que uno con 200. Pídelo aparte. 07 · Baila la primera canción mirándose a los ojos, no a la cámara. Te lo prometemos." },
      { layout: "imageText", image: img("weddingMoody", 35),
        eyebrow: "Consejos 08 a 10",
        titleParts: [{ text: "DESPUÉS" }, { text: "del sí", italic: true }],
        list: [
          "08 · Pide una sesión post-boda. La presión bajó. Sale magia.",
          "09 · Imprime al menos 20 fotos. El disco duro no es álbum.",
          "10 · Llámanos para tu próximo capítulo — embarazo, familia, lo que venga.",
        ]},
      { layout: "credits", tag: "Hablemos pronto" },
    ],
  },

  // 3. PACKS FAMILIARES
  {
    id: "familiares",
    unit: "Fotito Estudio",
    icon: "👨‍👩‍👧",
    brand: "Fotito Estudio",
    title: "Packs Familiares · 2026",
    coverImage: img("family", 41),
    pages: [
      { layout: "cover", brand: "FOTITO ESTUDIO", eyebrow: "Familia · 2026",
        titleParts: [{ text: "TU FAMILIA" }, { text: "en imagen", italic: true }],
        script: "Historias de familias",
        image: img("family", 41), no: "03" },
      { layout: "index", eyebrow: "Contenido", titleParts: [{ text: "TRES" }, { text: "paquetes", italic: true }],
        items: [
          { name: "Pack Esencia", page: 4 },
          { name: "Pack Armonía", page: 6 },
          { name: "Pack Legado", page: 8 },
          { name: "Cómo agendar", page: 10 },
        ]},
      { layout: "imageText", image: img("family", 42),
        eyebrow: "Introducción",
        titleParts: [{ text: "EL TRATO" }, { text: "humano", italic: true }],
        body: "Nuestras sesiones familiares no se gestionan por formulario. Conversamos primero — entendemos la dinámica, los miedos a la cámara, las personalidades — y luego hacemos magia." },
      { layout: "package", eyebrow: "Familiar · 01", no: "01",
        titleParts: [{ text: "Esencia" }, { text: "Familiar", italic: true }],
        price: "70.000",
        list: [
          "Sesión en estudio o locación",
          "10 fotos editadas, alta resolución",
          "Hasta 4 personas",
          "Galería web privada",
          "Asesoría de poses incluida",
        ]},
      { layout: "package", eyebrow: "Familiar · 02 · Más elegido", no: "02",
        titleParts: [{ text: "Armonía" }, { text: "Familiar", italic: true }],
        price: "120.000",
        list: [
          "Sesión en estudio o locación",
          "20 fotos editadas",
          "Hasta 5 personas",
          "Galería web privada",
          "1 outfit + accesorios sugeridos",
        ],
        note: "★ El más elegido por familias de Buin y alrededores" },
      { layout: "fullImage", image: img("family", 43),
        captionLabel: "Familia · Sesión real",
        caption: "Para Rosa, una sesión familiar nunca es solo fotos — es darse cuenta de cómo se quieren." },
      { layout: "package", eyebrow: "Familiar · 03 · Premium", no: "03",
        titleParts: [{ text: "Legado" }, { text: "Signature", italic: true }],
        price: "200.000",
        list: [
          "Sesión 2 horas, estudio + locación",
          "40 fotos editadas",
          "Photobook físico 25x25",
          "Sin límite de personas",
          "Asesoría de vestuario por @rosaumbria",
        ],
        note: "Incluye entrega presencial del photobook" },
      { layout: "quote", quote: "Las fotos llegaron justo en mi cumpleaños. Mi mamá lloró cuando las vio.", by: "Paulina · Cliente 2024" },
      { layout: "credits", tag: "Reservemos" },
    ],
  },

  // 4. SMASH CAKE
  {
    id: "smash",
    unit: "Fotito Estudio",
    icon: "🎂",
    brand: "Fotito Estudio",
    title: "Smash Cakes · 2026",
    coverImage: img("smashCake", 51),
    pages: [
      { layout: "cover", brand: "FOTITO ESTUDIO", eyebrow: "Smash · 2026",
        titleParts: [{ text: "SMASH" }, { text: "cake", italic: true }],
        script: "Su primer año, en portada",
        image: img("smashCake", 51), no: "04" },
      { layout: "imageText", image: img("smashCake", 52),
        eyebrow: "Smash Cake",
        titleParts: [{ text: "EL PRIMER" }, { text: "cumpleaños", italic: true }],
        body: "Tu hijo o hija solo cumple un año una vez. Nuestro set incluye torta artesanal, decoración temática, paciencia infinita y mucha luz natural." },
      { layout: "package", eyebrow: "Smash · 01", no: "01",
        titleParts: [{ text: "Smash" }, { text: "Dulce", italic: true }],
        price: "90.000",
        list: [
          "Sesión 45 min en estudio",
          "Torta artesanal incluida",
          "10 fotos editadas",
          "Set temático básico",
          "Galería web privada",
        ]},
      { layout: "package", eyebrow: "Smash · 02 · Más elegido", no: "02",
        titleParts: [{ text: "Smash" }, { text: "Premium", italic: true }],
        price: "150.000",
        list: [
          "Sesión 1.5 horas",
          "Torta artesanal + frutas + globos",
          "20 fotos editadas",
          "Set temático personalizado",
          "Cambio de outfit incluido",
        ],
        note: "★ Incluye sesión pre-smash con vestidos" },
      { layout: "fullImage", image: img("smashCake", 53),
        captionLabel: "Smash · En cámara",
        caption: "Mucha torta, mucha risa, ningún apuro." },
      { layout: "quote", quote: "Pensé que iba a llorar. Se rió y comió torta dos horas. Las fotos son una obra de arte.", by: "Camila · Mamá de Antonia" },
      { layout: "credits", tag: "Agéndalo" },
    ],
  },

  // 5. PRENATALES
  {
    id: "prenatal",
    unit: "Fotito Estudio",
    icon: "🤰",
    brand: "Fotito Estudio",
    title: "Prenatales · 2026",
    coverImage: img("prenatal", 61),
    pages: [
      { layout: "cover", brand: "FOTITO ESTUDIO", eyebrow: "Prenatal · 2026",
        titleParts: [{ text: "ISABELLA" }, { text: "prenatal", italic: true }],
        script: "el comienzo, dorado",
        image: img("prenatal", 61), no: "05" },
      { layout: "imageText", image: img("prenatal", 62),
        eyebrow: "Sobre la sesión",
        titleParts: [{ text: "LA LUZ" }, { text: "dorada", italic: true }],
        body: "Nuestras sesiones prenatales usan tul, sedas y luz natural lateral para crear retratos editoriales. Ideal entre la semana 28 y 34 — cuando la pancita está hermosa pero aún cómoda." },
      { layout: "package", eyebrow: "Prenatal · 01", no: "01",
        titleParts: [{ text: "Aurora" }],
        price: "120.000",
        list: [
          "Sesión 1 hora en estudio",
          "15 fotos editadas",
          "1 outfit (vestidos de estudio incluidos)",
          "Galería web privada",
        ]},
      { layout: "package", eyebrow: "Prenatal · 02 · Recomendado", no: "02",
        titleParts: [{ text: "Isabella", italic: true }],
        price: "180.000",
        list: [
          "Sesión 2 horas en estudio",
          "25 fotos editadas",
          "2 outfits + accesorios dorados",
          "Maquillaje y peinado por @rosaumbria",
          "Sesión con pareja incluida",
        ],
        note: "★ Estética editorial dorada — la más pedida" },
      { layout: "fullImage", image: img("prenatal", 63),
        captionLabel: "Prenatal · Sesión Isabella",
        caption: "Tul dorado, luz lateral, silencio. Tu pancita merece este momento." },
      { layout: "quote", quote: "Las fotos del embarazo son las que más miro. Mi hijo va a saber cómo lo esperé.", by: "Antonia · Mamá primeriza" },
      { layout: "credits", tag: "Esperémoslo juntos" },
    ],
  },

  // 6. SESIONES ESPECIALES
  {
    id: "especiales",
    unit: "Fotito Estudio",
    icon: "✨",
    brand: "Fotito Estudio",
    title: "Sesiones Especiales · 2026",
    coverImage: img("portrait", 71),
    pages: [
      { layout: "cover", brand: "FOTITO ESTUDIO", eyebrow: "Marca Personal · 2026",
        titleParts: [{ text: "MARCA" }, { text: "personal", italic: true }],
        script: "tu imagen profesional",
        image: img("portrait", 71), no: "06" },
      { layout: "imageText", image: img("portrait", 72),
        eyebrow: "Para emprendedoras",
        titleParts: [{ text: "TU CARA" }, { text: "es tu marca", italic: true }],
        body: "Si tu negocio depende de tu imagen — coach, terapeuta, abogada, creadora — estas sesiones son para ti. Diseñamos cada toma pensando en redes, web y prensa." },
      { layout: "package", eyebrow: "Marca · 01", no: "01",
        titleParts: [{ text: "Básico" }],
        price: "80.000",
        list: [
          "Sesión en estudio o locación",
          "15 imágenes editadas",
          "Asesoría en poses y expresiones",
          "Portal digital personalizado",
        ]},
      { layout: "package", eyebrow: "Marca · 02", no: "02",
        titleParts: [{ text: "Profesional", italic: true }],
        price: "150.000",
        list: [
          "Sesión estudio o locación",
          "25 imágenes editadas",
          "Maquillaje y peinado básico",
          "Asesoría completa de poses",
          "Portal digital privado",
        ]},
      { layout: "package", eyebrow: "Marca · 03 · Premium", no: "03",
        titleParts: [{ text: "Premium" }],
        price: "250.000",
        list: [
          "1 hora estudio + 1 hora locación",
          "40 imágenes editadas",
          "Maquillaje y peinado profesional",
          "Asesoría completa de marca",
          "Entrega en 7 días hábiles",
        ],
        note: "★ Recomendado para campañas y prensa" },
      { layout: "fullImage", image: img("portrait", 73),
        captionLabel: "Marca · Sesión Premium",
        caption: "Una buena foto profesional dura tres años en tu LinkedIn. Vale cada peso." },
      { layout: "credits", tag: "Tu marca" },
    ],
  },

  // 7. PACK OCASIÓN
  {
    id: "ocasion",
    unit: "Fotito Estudio",
    icon: "🎉",
    brand: "Fotito Estudio",
    title: "Pack Ocasión · 2026",
    coverImage: img("family", 81),
    pages: [
      { layout: "cover", brand: "FOTITO ESTUDIO", eyebrow: "Cumpleaños & Parejas",
        titleParts: [{ text: "OCASIÓN" }, { text: "2026", italic: true }],
        script: "celebrar es recordar",
        image: img("family", 81), no: "07" },
      { layout: "twoColumn", eyebrow: "Para esta edición",
        titleParts: [{ text: "DOS" }, { text: "líneas", italic: true }],
        body: "Cumpleañeras — sesiones para celebrar tus años con la mejor versión de ti, con o sin maquillaje profesional, en estudio o exterior.",
        body2: "Parejas — para aniversarios, propuestas, o sin motivo. Porque a veces lo que se quiere también necesita estar fotografiado." },
      { layout: "package", eyebrow: "Cumpleañera · Pack Dulce", no: "01",
        titleParts: [{ text: "Dulce" }],
        price: "80.000",
        list: [
          "Sesión en estudio",
          "15 imágenes editadas",
          "1 outfit",
          "Guía de poses",
        ]},
      { layout: "package", eyebrow: "Cumpleañera · Pack Fiesta", no: "02",
        titleParts: [{ text: "Fiesta", italic: true }],
        price: "150.000",
        list: [
          "Sesión en estudio",
          "25 imágenes editadas",
          "Hasta 2 outfits",
          "Asesoría de vestuario y paleta",
          "Maquillaje y peinado social",
        ]},
      { layout: "package", eyebrow: "Cumpleañera · Pack Celebración", no: "03",
        titleParts: [{ text: "Celebración" }],
        price: "200.000",
        list: [
          "Sesión 2 horas, estudio o exterior",
          "35 imágenes editadas",
          "Hasta 3 outfits",
          "Maquillaje y peinado profesional",
        ]},
      { layout: "package", eyebrow: "Parejas · Pack Amor", no: "04",
        titleParts: [{ text: "Amor", italic: true }],
        price: "60.000",
        list: [
          "Sesión en estudio",
          "15 imágenes editadas",
          "Asesoría de poses para parejas",
        ]},
      { layout: "package", eyebrow: "Parejas · Pack Romance", no: "05",
        titleParts: [{ text: "Romance" }],
        price: "100.000",
        list: [
          "Sesión en estudio",
          "25 imágenes editadas",
          "Maquillaje y peinado básico por @rosaumbria",
        ]},
      { layout: "credits", tag: "Celebremos" },
    ],
  },

  // 8. PACKS ROSA UMBRÍA
  {
    id: "rosa",
    unit: "Rosa Umbría",
    icon: "💄",
    brand: "Rosa Umbría",
    title: "Packs Rosa · 2025",
    coverImage: img("makeup", 91),
    pages: [
      { layout: "cover", brand: "ROSA UMBRÍA", eyebrow: "Makeup & Hair · 2025",
        titleParts: [{ text: "ROSA" }, { text: "umbría", italic: true }],
        script: "novias, sesiones y eventos",
        image: img("makeup", 91), no: "08" },
      { layout: "imageText", image: img("makeup", 92),
        eyebrow: "Sobre Rosa",
        titleParts: [{ text: "MAQUILLAJE" }, { text: "que dura", italic: true }],
        body: "Rosa lleva 8 años maquillando novias y modelos en Buin y Santiago. Su sello es la luminosidad natural — pieles que se ven piel, no máscaras, incluso al final de la noche." },
      { layout: "package", eyebrow: "Novia · Pack Esencial", no: "01",
        titleParts: [{ text: "Novia" }, { text: "esencial", italic: true }],
        price: "180.000",
        list: [
          "Prueba previa de maquillaje y peinado",
          "Maquillaje el día de la boda",
          "Peinado completo",
          "Retoque hasta el primer baile",
        ]},
      { layout: "package", eyebrow: "Novia · Pack Atelier", no: "02",
        titleParts: [{ text: "Novia" }, { text: "Atelier" }],
        price: "280.000",
        list: [
          "Prueba previa completa",
          "Maquillaje + peinado el día",
          "2 retoques durante el día",
          "Maquillaje para mamá de la novia",
          "Kit emergencia incluido",
        ],
        note: "★ Para bodas en formato editorial" },
      { layout: "package", eyebrow: "Sesiones · Pack", no: "03",
        titleParts: [{ text: "Sesión", italic: true }],
        price: "60.000",
        list: [
          "Maquillaje social",
          "Peinado básico (ondas o recogido)",
          "Para sesiones de fotos de Fotito Estudio",
        ]},
      { layout: "credits", tag: "Hablemos" },
    ],
  },

  // 9. VIDA GRADO
  {
    id: "grado",
    unit: "Graduaciones",
    icon: "🎓",
    brand: "Umbría Studio",
    title: "Vida Grado · 2025",
    coverImage: img("graduation", 101),
    pages: [
      { layout: "cover", brand: "UMBRÍA STUDIO", eyebrow: "Graduaciones · 2025",
        titleParts: [{ text: "VIDA" }, { text: "grado", italic: true }],
        script: "el logro que dura",
        image: img("graduation", 101), no: "09" },
      { layout: "twoColumn", eyebrow: "Para colegios",
        titleParts: [{ text: "EL DÍA" }, { text: "que se recuerda", italic: true }],
        body: "Cubrimos graduaciones de colegios, institutos y universidades en Santiago y Región Metropolitana. Trabajamos con equipos de 2 a 4 fotógrafos según tamaño del evento.",
        body2: "Nuestro estilo: editorial y emocional. No solo el diploma — también el abrazo del papá, la lágrima de la profesora, el grito final al lanzar el birrete." },
      { layout: "package", eyebrow: "Grado · Básico", no: "01",
        titleParts: [{ text: "Cobertura" }, { text: "esencial", italic: true }],
        price: "350.000",
        list: [
          "Cobertura 2 horas, 2 fotógrafos",
          "Foto individual con diploma",
          "100+ imágenes editadas",
          "Portal web privado por curso",
        ]},
      { layout: "package", eyebrow: "Grado · Premium", no: "02",
        titleParts: [{ text: "Cobertura" }, { text: "completa" }],
        price: "650.000",
        list: [
          "Cobertura 4 horas, 3 fotógrafos",
          "Sesión retrato por alumno",
          "300+ imágenes editadas",
          "Video resumen del evento",
          "Photobook por curso (1 unidad)",
        ],
        note: "★ Incluye sesión familia + alumno separada" },
      { layout: "fullImage", image: img("graduation", 102),
        captionLabel: "Graduación · Universidad",
        caption: "Cuatro años de estudio, cinco minutos en el escenario, una foto para siempre." },
      { layout: "credits", tag: "Coordinemos" },
    ],
  },
];

// Helper to find by id
window.UMBRIA_GET_MAG = (id) => window.UMBRIA_MAGAZINES.find(m => m.id === id);
